name: Publish Docs

on:
  workflow_dispatch:

  push:
    branches:
      - main
    tags:
      - "docs-v*"
    paths:
      - ".github/workflows/documentation.yml"
      - "docs/**"
      - "zensical.toml"
      - "overrides/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/documentation.yml"
      - "docs/**"
      - "zensical.toml"
      - "overrides/**"

permissions:
  contents: read

jobs:

  docs_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install zensical mkdocstrings-python

      - name: Build docs
        run: |
          python tools/build_doc.py
          ls -la site/

      - name: Upload docs site
        uses: actions/upload-artifact@v7
        with:
          name: docs-site
          path: site/
          retention-days: 14

      - uses: actions/upload-artifact@v7
        with:
          name: docs-archive
          path: documentation*.zip
          retention-days: 14

  docs_publish:
    if: startsWith(github.ref_name, 'docs-v')
    needs: docs_build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download docs site
        uses: actions/download-artifact@v8
        with:
          name: docs-site
          path: site

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
